# Generated by Django 2.1.1.dev20180917144049 on 2018-10-07 08:23

from django.db import migrations, models
import jcb.models.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JcbReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='ご利用者')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('used_on', models.DateField(blank=True, default=None, null=True, verbose_name='ご利用日')),
                ('shop', models.CharField(max_length=100, verbose_name='ご利用先など')),
                ('used_amount', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=7, null=True, verbose_name='ご利用金額(￥)')),
                ('payment', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='支払区分')),
                ('paynumber', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='今回回数')),
                ('correction', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='訂正サイン')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=7, null=True, verbose_name='お支払い金額(￥)')),
                ('national', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='国内／海外')),
                ('summary', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='摘要')),
                ('remarks', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'JCB明細',
                'verbose_name_plural': 'JCB明細',
            },
            bases=(models.Model, jcb.models.methods.JcbReceipt),
        ),
        migrations.CreateModel(
            name='JcbShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jcbreceipt',
            unique_together={('used_on', 'shop', 'used_amount')},
        ),
    ]
