# Generated by Django 2.1.1.dev20180915035250 on 2018-09-17 10:01

import books.models.methods
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mymedia.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('data', models.FileField(upload_to=mymedia.files.ModelFieldPath('data'))),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'permissions': (('download_data', 'Download Data'),),
            },
            bases=(models.Model, books.models.methods.Attachment),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('branch', models.CharField(max_length=50, verbose_name='Bank Branch Name')),
                ('holder', models.CharField(max_length=50, verbose_name='Account Holder Name')),
                ('account_type', models.CharField(choices=[('普通', '普通'), ('当座', '当座')], max_length=10, verbose_name='Account Type')),
                ('account', models.CharField(max_length=20, verbose_name='Account Number')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('family_name', models.CharField(max_length=50, verbose_name='Faminly Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('job_title', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Job Title')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FisicalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Fisical Year Name')),
            ],
            options={
                'verbose_name': 'FiscalYear',
                'verbose_name_plural': 'FiscalYears',
            },
            bases=(models.Model, books.models.methods.FisicalYear),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Invoice Title')),
                ('sub_title', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Invoice Sub Title')),
                ('number', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Total Amount')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Amount')),
                ('tax', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Tax')),
                ('rmarks', models.TextField(blank=True, default=None, null=True, verbose_name='Invoice Remarks')),
                ('due_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Due At')),
                ('closed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Closed At')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
            bases=(models.Model, books.models.methods.Invoice),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Origanization Name')),
                ('division', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Origanization Divition')),
                ('postal_code', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Postal Code')),
                ('prefecture', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Prefecture')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City')),
                ('town', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Town')),
                ('building', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Building')),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Fax')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Organization', verbose_name='Payment To')),
            ],
            options={
                'verbose_name': 'Payment Invoice',
                'verbose_name_plural': 'Payment Invoices',
            },
            bases=('books.invoice', models.Model),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Organization', verbose_name='Receipt From')),
            ],
            options={
                'verbose_name': 'Receipt Invoice',
                'verbose_name_plural': 'Receipt Invoices',
            },
            bases=('books.invoice', models.Model),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fisical_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.FisicalYear', verbose_name='Fisical Year'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subclass_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Subclass Type'),
        ),
        migrations.AddField(
            model_name='fisicalyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='bank',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Organization', verbose_name='Organization'),
        ),
    ]
